export const AVAILABLE_ICONS = [
  'Utensils',
  'Fuel',
  'Milk',
  'Egg',
  'ShoppingCart',
  'Car',
  'Home',
  'Coffee',
  'Film',
  'HeartPulse',
  'Zap',
  'Wifi',
  'Phone',
  'BookOpen',
  'GraduationCap',
  'Plane',
  'Briefcase',
  'Gift',
  'Dumbbell',
  'Shirt',
  'ShieldCheck',
  'Sparkles',
];

export const CURRENCY_OPTIONS = [
  { code: 'INR', symbol: '₹', name: 'Indian Rupee (₹)' },
  { code: 'USD', symbol: '$', name: 'US Dollar ($)' },
  { code: 'EUR', symbol: '€', name: 'Euro (€)' },
  { code: 'GBP', symbol: '£', name: 'British Pound (£)' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen (¥)' },
  { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar (CA$)' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar (A$)' },
  { code: 'AED', symbol: 'AED', name: 'UAE Dirham (AED)' },
];
